downgrade setuptools
the pinned version was causing the following error during pip install:

ERROR: Cannot install -r requirements.txt (line 19) and setuptools~=67.8.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested setuptools~=67.8.0
    spice-jitter-correction 2022.2.1 depends on setuptools==63.1.0